#连接Mirai的WS Url
connectUrl: ws://127.0.0.1:8081

#Mirai连接key
key: INITKEYVYTWM9qc

#Mirai连接qq
qq: 3544175039

#发消息群聊
group: 
  - 615056067

#有权限操作机器人的qq
admin:
  - 2351078777

#关闭服务器的命令
stopCmd: stop

#最低输出等级
LoggerLevel: debug

#检测玩家改名
checkNick: true

#屏蔽改名
DisableNick:
  - 235107

#退群自动删除白名单
AutoDeleteWhiteList: true

#未绑定白名单不能发言
AutoRecall: true

#绑定自动改群名片
AutoNick: true

#自动改群名片白名单
AutoNickWhiteList: []

#自动改变机器人名称
AutoChangeBotName:
  #启用此功能
  Enable: true
  #改变的字符串 %Online%在线人数 %Max%最大人数
  String: '[Bot] 服务器在线:%Online%/%Max%'
  #关服自动还原的昵称(注：还原原名称请填写'',不开启请设置false)
  StopReset: '[Bot] 我是机器人'

#配置文件版本(勿动)
Version: 1